version: "3.8"



services:

  node_install:
    container_name: node_install_page
    image: "node:14"
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app
    environment:
      TZ: "${TZ}"

    command: sh -c "npm install"











